export const STATUS_OPTIONS = [
  { value: "In_Use", label: "In Use" },
  { value: "Not_Using", label: "Not Using" },
  { value: "Broken", label: "Broken" },
  { value: "Service_Required", label: "Service Required" },
  { value: "Not_serviceable", label: "Not serviceable" },
  { value: "Discarded", label: "Discarded" },
  { value: "Missing", label: "Missing" },
];

export const PRODUCT_NAME_OPTIONS = [
  { value: "Laptop", label: "Laptop" },
  { value: "Desktop", label: "Desktop" },
  { value: "Mouse", label: "Mouse" },
  { value: "Mouse_Pad", label: "Mouse Pad" },
  { value: "Cooling_Pad", label: "Cooling Pad" },
  { value: "Head_Phone", label: "HeadPhone" },
  { value: "Web_Camera", label: "Web-Camera" },
  { value: "Keyboard", label: "Keyboard" },
  { value: "Laptop_Bag", label: "Laptop Bag" },
  { value: "Trolley_Bag", label: "Trolley Bag" },
  { value: "Electrical_Extension_Box", label: "Electrical Extension Box" },
  { value: "Table", label: "Table" },
  { value: "Wheel_Chair", label: "Wheel Chair" },
  { value: "Plastic_Chair", label: "Plastic Chair" },
  { value: "Rotatable_Chair", label: "Rotatable Chair" },
  { value: "Table_Fan", label: "Table Fan" },
  { value: "Pen_Drive", label: "Pen Drive" },
  { value: "Biometric_Device", label: "Biometric Device" },
  { value: "Hard_Disk", label: "Hard Disk" },
  { value: "Apple_USB_Box", label: "Apple USB Box" },
  { value: "Camera", label: "Camera" },
  { value: "Camera_Stand", label: "Camera Stand" },
  { value: "Camera_Mount", label: "Camera Mount" },
  { value: "Studio_Light", label: "Studio Light" },
  { value: "iPhone", label: "iPhone" },
  { value: "Feature_Phone", label: "Feature Phone" },
  { value: "Speaker", label: "Speaker" },
  { value: "Mic", label: "Mic" },
  { value: "WiFi_Dongle", label: "WiFi Dongle" },
  { value: "WiFi_Router", label: "WiFi Router" },
  { value: "AC", label: "AC" },
  { value: "Book_Stand", label: "Book Stand" },
  { value: "Service_Tool", label: "Service Tool" },
  { value: "Mosquito_Bat", label: "Mosquito Bat" },
  { value: "Printer", label: "Printer" },
  { value: "HDMI_Cable", label: "HDMI Cable" },
  { value: "Projector", label: "Projector" },
  { value: "Smart_Board", label: "Smart Board" },
  { value: "White_Board", label: "White Board" },
  { value: "Duster", label: "Duster" },
  { value: "Game_Element", label: "Game Element" },
  { value: "Others", label: "Others" },
];

export const ASSET_LOCATIONS = [
  { value: "Bengaluru", label: "KA - Bengaluru" },
  { value: "Tirupur", label: "TN - Tirupur" },
];

// If you have other common constants, you can add them here or in a commonConstants.js
export const DEFAULT_PAGE_SIZE = 10;
